name: aplikasi_rw
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #font awes
  font_awesome_flutter: ^10.2.1
  # image picker tanpa null safety
  image_picker: ^0.8.6
  #carousel card
  carousel_slider: ^4.1.1
  #indicator news
  smooth_page_indicator: ^1.0.0+2
  # cache untuk image
  cached_network_image: ^3.2.3
  # flutter bloc
  flutter_bloc: ^8.1.1
  # http 
  http: ^0.13.5
  # readmore
  readmore: ^2.2.0
  # open whatsapp
  whatsapp_unilink: ^2.1.0
  # open url
  url_launcher: ^6.1.7
  # slideable
  flutter_slidable: ^2.0.0
  # introduction screen login
  introduction_screen: ^3.1.1
  # device preview
  # device_preview: ^0.5.5
  # sizer for responsive
  sizer: ^2.0.15
  # lottie error animation
  lottie: ^2.0.0
  # secure storage
  flutter_secure_storage: ^6.1.0
  # timeline
  timeline_tile: ^2.0.0
  # stepper
  im_stepper: ^1.0.1+1
  google_maps_flutter: ^2.2.1
  location: ^4.4.0
  geocoder: ^0.2.1
  shimmer: ^2.0.0
  # string_to_color: ^1.0.1
  badges: ^2.0.3
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.6.0
  stop_watch_timer: ^1.1.0+1
  get: ^4.6.5
  firebase_messaging: ^14.1.2
  firebase_core: ^2.3.0
  awesome_notifications: ^0.7.4+1
  logger: ^1.1.0
  showcaseview: ^2.0.0+1
  table_calendar: ^3.0.8
  intl: ^0.17.0
  async: ^2.9.0
  connectivity_plus: ^3.0.2
  device_info_plus: ^8.0.0
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_charts: ^20.3.59
  fluttertoast: ^8.1.1
  flutter_holo_date_picker: ^1.1.0
  sliding_up_panel: ^2.0.0+1
  flutter_google_places: ^0.3.0
  grouped_buttons: ^1.0.4
  pin_code_fields: ^7.4.0
  dio: ^4.0.6
  http_parser: ^4.0.2
  flutter_easyloading: ^3.0.5
  camera: ^0.10.1
  dio_smart_retry: ^1.4.0
  auto_size_text: ^3.0.0
  like_button: ^2.0.5
  photo_manager: ^2.5.2
  flutter_html: ^3.0.0-alpha.3
  package_info_plus: ^3.0.2

  
  
  
  
  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo_rw.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ca/
    - assets/img/
    - assets/img/citizen_menu/
    - assets/img/estate_manager_menu/
    - assets/img/image-icons/
    - assets/img/cordinator/
    - assets/img/image-onboarding/
    - assets/img/image-svg/
    - assets/animation/
  #   - assets/img/background-pattern.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  #         style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Saira Condensed
      fonts:
        - asset: assets/fonts/SairaCondensed-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: Montserrat 
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: NewsCycle 
      fonts:
        - asset: assets/fonts/NewsCycle-Regular.ttf

    


  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
