// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAko9Q8YypNtyau7DmCnWRDDTSwA_IChpM',
    appId: '1:949444304688:android:462c378077d3431ed3b2f5',
    messagingSenderId: '949444304688',
    projectId: 'nextgmobileapprw05bgmpik',
    storageBucket: 'nextgmobileapprw05bgmpik.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYTrNX6VhtjHWnb5LmCdhGovTe6ShekFs',
    appId: '1:949444304688:ios:24cece94726dea1cd3b2f5',
    messagingSenderId: '949444304688',
    projectId: 'nextgmobileapprw05bgmpik',
    storageBucket: 'nextgmobileapprw05bgmpik.appspot.com',
    androidClientId: '949444304688-ito33llo34vv6fulcmagtrd5re5mbl5p.apps.googleusercontent.com',
    iosClientId: '949444304688-3jjqsi3l1phdpc0akco40ev8bc5ko6mf.apps.googleusercontent.com',
    iosBundleId: 'com.nextg.rw05bgmpik',
  );
}
